# Generated by Django 3.0.7 on 2022-11-27 18:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('oit', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Notes',
            new_name='Books',
        ),
    ]
