# Generated by Django 3.0.7 on 2022-11-28 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oit', '0002_auto_20221127_2112'),
    ]

    operations = [
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('picture', models.CharField(max_length=100)),
                ('age', models.CharField(max_length=100)),
                ('birthday', models.CharField(max_length=100)),
            ],
        ),
        migrations.RenameModel(
            old_name='Books',
            new_name='Book',
        ),
    ]
