name: hello-world
on: push
jobs:
    testing1:
        runs-on: ubuntu-latest
        steps:
          - name: hello
            run: echo "Hello World!"
    testing2:
        runs-on: ubuntu-latest
        needs: [testing1]
        steps:
          - name: hello with color
            run:
             echo -e "\033[35mHello \033[34mworld \033[32mпривет \033[33mмир \033[31mи пока\033[0m"
