name: hello-world
on: push
jobs:
  my-job:
    runs-on: ubuntu-latest
    testing1:
       steps:
        - name: hello world
          run: echo "Hello World!"
    testing2:
      needs: [testing1]
      steps:
        - name: hello oit
          run:
            export VAR=oit
            echo "Здарова, это проект по" $VAR
