name: hello-world
on: push
jobs:
  my-job:

    testing1:
        runs-on: ubuntu-latest
        steps:
          - name: hello world
            run: echo "Hello World!"
    testing2:
        runs-on: ubuntu-latest
        needs: [testing1]
        steps:
          - name: hello oit
            run:
              export VAR=oit
              echo "Здарова, это проект по $VAR"
